export type DoctorAppointment = {
  id: number;
  doctorId: number;
  title: string;
  person: string;
  date: string;
  booked: boolean;
};

export const DOCTOR_APPOINTMENTS: DoctorAppointment[] = [
  {
    id: 1,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-05-01 10:00",
    booked: false,
  },
  {
    id: 2,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-05-08 10:00",
    booked: false,
  },
  {
    id: 3,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-05-15 10:00",
    booked: false,
  },
  {
    id: 4,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-05-22 10:00",
    booked: false,
  },
  {
    id: 5,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-05-29 10:00",
    booked: false,
  },
  {
    id: 6,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-05-02 09:00",
    booked: false,
  },
  {
    id: 7,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-05-09 09:00",
    booked: false,
  },
  {
    id: 8,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-05-16 09:00",
    booked: false,
  },
  {
    id: 9,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-05-23 09:00",
    booked: false,
  },
  {
    id: 10,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-05-30 09:00",
    booked: false,
  },
  {
    id: 11,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-05-03 12:30",
    booked: false,
  },
  {
    id: 12,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-05-10 12:30",
    booked: false,
  },
  {
    id: 13,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-05-17 12:30",
    booked: false,
  },
  {
    id: 14,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-05-24 12:30",
    booked: false,
  },
  {
    id: 15,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-05-31 12:30",
    booked: false,
  },
  {
    id: 16,
    doctorId: 4,
    title: "Stomatolog",
    person: "Dr. Karol Wojteka",
    date: "2024-05-06 10:00",
    booked: false,
  },
  {
    id: 17,
    doctorId: 4,
    title: "Stomatolog",
    person: "Dr. Karol Wojteka",
    date: "2024-05-13 10:00",
    booked: false,
  },
  {
    id: 18,
    doctorId: 4,
    title: "Stomatolog",
    person: "Dr. Karol Wojteka",
    date: "2024-05-20 10:00",
    booked: false,
  },
  {
    id: 19,
    doctorId: 4,
    title: "Stomatolog",
    person: "Dr. Karol Wojteka",
    date: "2024-05-27 10:00",
    booked: false,
  },
  {
    id: 20,
    doctorId: 5,
    title: "Diabetolog",
    person: "Dr. Magdalena Kowalska",
    date: "2024-05-07 14:00",
    booked: false,
  },
  {
    id: 21,
    doctorId: 5,
    title: "Diabetolog",
    person: "Dr. Magdalena Kowalska",
    date: "2024-05-14 14:00",
    booked: false,
  },
  {
    id: 22,
    doctorId: 5,
    title: "Diabetolog",
    person: "Dr. Magdalena Kowalska",
    date: "2024-05-21 14:00",
    booked: false,
  },
  {
    id: 23,
    doctorId: 5,
    title: "Diabetolog",
    person: "Dr. Magdalena Kowalska",
    date: "2024-05-28 14:00",
    booked: false,
  },
  {
    id: 24,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-05-06 11:00",
    booked: false,
  },
  {
    id: 25,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-05-13 11:00",
    booked: false,
  },
  {
    id: 26,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-05-20 11:00",
    booked: false,
  },
  {
    id: 27,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-05-27 11:00",
    booked: false,
  },
  {
    id: 28,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-06-03 11:00",
    booked: false,
  },
  {
    id: 29,
    doctorId: 1,
    title: "Kardiolog",
    person: "Dr. Krzysztof Zjadek",
    date: "2024-06-05 10:00",
    booked: false,
  },
  {
    id: 30,
    doctorId: 2,
    title: "Neurolog",
    person: "Dr. Karina Wojska",
    date: "2024-06-06 09:00",
    booked: false,
  },
  {
    id: 31,
    doctorId: 3,
    title: "Ortopeda",
    person: "Dr. Karol Poss",
    date: "2024-06-07 12:30",
    booked: false,
  },
  {
    id: 32,
    doctorId: 4,
    title: "Stomatolog",
    person: "Dr. Karol Wojteka",
    date: "2024-06-10 10:00",
    booked: false,
  },
  {
    id: 33,
    doctorId: 5,
    title: "Diabetolog",
    person: "Dr. Magdalena Kowalska",
    date: "2024-06-11 14:00",
    booked: false,
  },
  {
    id: 34,
    doctorId: 6,
    title: "Pediatra",
    person: "Dr. Szymon Szczepała",
    date: "2024-06-12 11:00",
    booked: false,
  },
];
